name: Deploy test_db branch to Databricks Shared Folder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Upload supported files to Databricks Shared Folder
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          # Allowed extensions for Databricks notebooks
          exts="py ipynb sql scala r dbc html"

          # Loop through repo and upload only supported files
          for file in $(find . -type f); do
            ext="${file##*.}"
            if [[ " $exts " == *" $ext "* ]]; then
              target_path="/Shared/ai/${file#./}"
              echo "Importing $file -> $target_path"
              databricks workspace import --overwrite "$file" "$target_path"
            else
              echo "Skipping unsupported file: $file"
            fi
          done
